### ISSUE TITLE
Error loading collections

### ISSUE THREAD

**Issue by StorytellerCZ** [jamauro/offline#4]
Getting the following error on client when I start my app:
```
Error loading collections DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.<anonymous> (http://localhost:4200/packages/jam_offline.js?hash=b7ef796fafac0b8710cc10ea42e96348bf2ddf71:1229:26)
    at Proxy.method (http://localhost:4200/packages/jam_offline.js?hash=b7ef796fafac0b8710cc10ea42e96348bf2ddf71:1332:25)
    at getAll (http://localhost:4200/packages/jam_offline.js?hash=b7ef796fafac0b8710cc10ea42e96348bf2ddf71:463:13)
    at async loadAndObserve (http://localhost:4200/packages/jam_offline.js?hash=b7ef796fafac0b8710cc10ea42e96348bf2ddf71:593:18)
    at async Promise.all (index 0)
    at async load (http://localhost:4200/packages/jam_offline.js?hash=b7ef796fafac0b8710cc10ea42e96348bf2ddf71:633:5)
```
It traces to the `wrapFunction`, to the last return there.

**Comment by jamauro** [comment]
Are you seeing this after a HMR by chance? I've seen a similar error in that case and I had to clear my indexeddb cache via the browser tools.

Otherwise, if you can provide some more detail on the circumstances where you saw the error, I'd really appreciate it.

**Comment by StorytellerCZ** [comment]
Likely, will pay more attention next time I see this for this case and report back.

**Comment by harry-73** [comment]
Have the same issue. I installed the package, start `meteor` and got this error in the console. 
So no datas are pushed to the IndexedDB 'db'

I use `METEOR@3.0.1`

**Comment by jamauro** [comment]
@harry-73 Thanks for reporting. Can you help me diagnose the issue by isolating in a simple repro? In the meantime, if you can share how you're setting up your Collections and any other packages you're using, that might provide some clues.

**Comment by harry-73** [comment]
I will try to reproduice in a repo.

My Collections are defined as below:

```
import { Mongo } from 'meteor/mongo';

const Markers = new Mongo.Collection('Markers', {
  idGeneration: 'MONGO'
});

Markers.before.insert(function (userId, doc) {
  doc.createdAt = new Date(moment.utc().format());
  doc.modifiedAt = new Date(moment.utc().format());
});

Markers.before.update(function (userId, doc, fieldNames, modifier, options) {
  modifier.$set = modifier.$set || {};
  modifier.$set.modifiedAt = new Date(moment.utc().format());
});

export default Markers;
```

**Comment by jamauro** [comment]
Ok I think I've figured out the issue. Will release a fix shortly after some more testing.

**Comment by jamauro** [comment]
Ok I just published `v0.1.2` which should resolve this issue. Be sure to clear your indexedDB before testing it out.

**Comment by harry-73** [comment]
It is now OK. 
I have no more the error and the collections are present in indexedDB. But, I am now facing another issue (#6 )

**Comment by jamauro** [comment]
Great thanks for confirming. I'll close this issue. 

I'll take a look at the other issue you opened soon. I think it requires adding support for Mongo id generation.

**Comment by wildhart** [comment]
I think I can still reproduce this issue, when **adding a new collection**, e.g. when releasing a new feature which I want available offline.

Steps to reproduce:

```ts
// code imported into client and server

console.log('creating Site Inspections collection...');
export const inspectionsCollection = new Mongo.Collection<SiteInspection>("inspections");

// console.log('creating Site Inspections Photos collection...');
// export const inspectionPhotosCollection = new Mongo.Collection<SitePhoto>("inspectionPhotos");

console.log('done!')
```

* Use the default `jam:offline` config, i.e. `keepAll: true`.
* Storage → "Clear Site Data"
* Load the page - note that the 2nd collection is commented.  Browser console.logs:
```
creating Site Inspections collection...
done!
```
* Uncomment the second collection, and wait for recompile and browser reload:
```
creating Site Inspections collection...
creating Site Inspections Photos collection...
done!
Error loading collections DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.<anonymous> (http://localhost:4000/packages/jam_offline.js?hash=a9350eb83042a799f649c113b3b0ee777304ecd2:1307:26)
    at Proxy.method (http://localhost:4000/packages/jam_offline.js?hash=a9350eb83042a799f649c113b3b0ee777304ecd2:1410:25)
    at getAll (http://localhost:4000/packages/jam_offline.js?hash=a9350eb83042a799f649c113b3b0ee777304ecd2:475:13)
    at async loadAndObserve (http://localhost:4000/packages/jam_offline.js?hash=a9350eb83042a799f649c113b3b0ee777304ecd2:609:18)
```
![image](https://github.com/user-attachments/assets/9a7d937a-b874-4135-8e85-808c1087e266)
* Keep reloading the page gives the same error
* Storage → "Clear Site Data" & Reload
* No more errors.

**Comment by harry-73** [comment]
I confirm also this behavior.

**Comment by jamauro** [comment]
> I think I can still reproduce this issue, when adding a new collection

Thanks for the repro details. I have fixed this in `v0.2.2`.

**Comment by wildhart** [comment]
I can confirm that `v0.2.2` works for me without the bug, thanks!
